---
img_root: xray_root
signal_to_noise_ratio: 0.7
multi_view_per_sample: true
to_each_view_its_own_label: false
experiments:
  train_set:
    annotations_path: inner_train_2023-12-22.csv
    num_jitters: 1
    spatial_transform: random
    shared_modalities:
      - ID
      - text
      - image
      - Exam_View
    modalities:
      BP_complications_hip:
        modality: output
        type: Multi_Bipolar
        to_each_view_its_own_label: false
        columns:
          - alt_AVN_any_any
          - alt_AVN_any_left
          - alt_AVN_any_right
          - alt_AVN_III_and_above
          - alt_AVN_implant_any
          - alt_AVN_implant_left
          - alt_AVN_implant_right
          - alt_AVN_IV_and_above
          - alt_AVN_V_and_above
          - alt_implant_stem_osteolysis_I_any
          - alt_implant_stem_osteolysis_I_left
          - alt_implant_stem_osteolysis_I_right
          - alt_implant_stem_osteolysis_II_any
          - alt_implant_stem_osteolysis_II_left
          - alt_implant_stem_osteolysis_II_right
          - alt_implant_stem_osteolysis_III_any
          - alt_implant_stem_osteolysis_III_left
          - alt_implant_stem_osteolysis_III_right
          - alt_implant_stem_osteolysis_IV_any
          - alt_implant_vancouver_B_any
          - alt_implant_vancouver_B_left
          - alt_implant_vancouver_B_right
          - alt_OA_I_or_II_any
          - alt_OA_I_or_II_left
          - alt_OA_I_or_II_right
          - alt_OA_III_or_IV_any
          - alt_OA_III_or_IV_left
          - alt_OA_III_or_IV_right
          - alt_osteolysis_AAOS_III_or_IV_any
          - alt_osteolysis_AAOS_III_or_IV_left
          - alt_osteolysis_AAOS_III_or_IV_right
          - alt_osteolysis_certain_AAOS_I_any
          - alt_osteolysis_certain_AAOS_I_large_any
          - alt_osteolysis_certain_AAOS_I_large_left
          - alt_osteolysis_certain_AAOS_I_large_right
          - alt_osteolysis_certain_AAOS_I_left
          - alt_osteolysis_certain_AAOS_I_right
          - Fracture
          - general_Angulation
          - general_AVN
          - general_AVN_II
          - general_AVN_III
          - general_AVN_IV
          - general_AVN_V
          - general_AVN_VI
          - general_Cast
          - general_Cast_minimal
          - general_Comminute
          - general_Complication
          - general_Dislocation
          - general_Displaced
          - general_Extra-articular
          - general_Fragment
          - general_Girdlestone
          - general_Girdlestone_left
          - general_Heterotopic
          - general_Implant
          - general_Intra-articular
          - general_Multiple
          - general_OA
          - general_OA_I
          - general_OA_I_left
          - general_OA_I_right
          - general_OA_II
          - general_OA_II_left
          - general_OA_II_right
          - general_OA_III
          - general_OA_III_left
          - general_OA_III_right
          - general_OA_IV
          - general_OA_IV_left
          - general_OA_IV_right
          - general_OA_left
          - general_OA_right
          - general_Oblique
          - general_Previous
          - general_Previous_1-3w
          - general_Previous_3_w+
          - general_Previous_callus
          - general_Previous_callus_minimal
          - general_Previous_callus_moderate
          - general_Previous_callus_rich
          - general_Previous_healed
          - general_Pseudo
          - general_Pseudo_atrophic
          - general_Pseudo_hypertrophic
          - general_Slightly_displaced
          - general_Spiral
          - general_Transverse
          - general_Tumor
          - general_Tumor_benign
          - general_Tumor_malignant
          - general_Tumor_malignant_lytic
          - general_Tumor_malignant_sclerotic
          - general_Undisplaced
          - general_Wedge
          - implant_Arthroplasty
          - implant_Cerclage
          - implant_Cerclage_fracture
          - implant_Collapse
          - implant_Cut-out
          - implant_DHS
          - implant_DHS_AVN
          - implant_DHS_AVN_right
          - implant_DHS_cutout
          - implant_DHS_cutout_right
          - implant_DHS_left
          - implant_DHS_loss_of_offset
          - implant_DHS_loss_of_offset_left
          - implant_DHS_loss_of_offset_right
          - implant_DHS_right
          - implant_Fixation_failure
          - implant_Hardware_fracture
          - implant_Hardware_migration
          - implant_Hemi
          - implant_hemi_Hemi
          - implant_hemi_Hemi_cement
          - implant_hemi_Hemi_cement_left
          - implant_hemi_Hemi_cement_right
          - implant_hemi_Hemi_dislocation
          - implant_hemi_Hemi_dislocation_posterior
          - implant_hemi_Hemi_dislocation_posterior_right
          - implant_hemi_Hemi_dislocation_right
          - implant_hemi_Hemi_erosion
          - implant_hemi_Hemi_erosion_minimal
          - implant_hemi_Hemi_erosion_right
          - implant_hemi_Hemi_fracture
          - implant_hemi_Hemi_left
          - implant_hemi_Hemi_osteolysis
          - implant_hemi_Hemi_osteolysis_II
          - implant_hemi_Hemi_osteolysis_II_right
          - implant_hemi_Hemi_osteolysis_right
          - implant_hemi_Hemi_right
          - implant_hemi_Hemi_uncemented
          - implant_hemi_Hemi_uncemented_left
          - implant_hemi_Hemi_uncemented_right
          - implant_IM-nail
          - implant_IM-nail_femur
          - implant_IM-nail_femur_atypical
          - implant_IM-nail_femur_atypical_right
          - implant_IM-nail_femur_cutout
          - implant_IM-nail_femur_cutout_left
          - implant_IM-nail_femur_cutout_right
          - implant_IM-nail_femur_left
          - implant_IM-nail_femur_long
          - implant_IM-nail_femur_long_left
          - implant_IM-nail_femur_long_right
          - implant_IM-nail_femur_loss_of_offset
          - implant_IM-nail_femur_loss_of_offset_left
          - implant_IM-nail_femur_loss_of_offset_right
          - implant_IM-nail_femur_right
          - implant_IM-nail_femur_short
          - implant_IM-nail_femur_short_left
          - implant_IM-nail_femur_short_right
          - implant_Implant_failure
          - implant_Insignificant
          - implant_Peri-implant_fracture
          - implant_Plate
          - implant_Plate_left
          - implant_Plate_right
          - implant_Screws
          - implant_Screws_joint_AVN
          - implant_Screws_joint_AVN_left
          - implant_Screws_joint_AVN_right
          - implant_Screws_joint_loss_of_alignment
          - implant_Screws_joint_loss_of_alignment_left
          - implant_Screws_joint_loss_of_alignment_right
          - implant_Screws_joint_migration
          - implant_Screws_joint_migration_left
          - implant_Screws_joint_migration_right
          - implant_Screws_joint_penetration
          - implant_Screws_joint_penetration_left
          - implant_Screws_joint_penetration_right
          - implant_Screws_left
          - implant_Screws_right
          - implant_THR
          - implant_thr_THR
          - implant_thr_THR_atypical
          - implant_thr_THR_atypical_constrained_liner
          - implant_thr_THR_atypical_constrained_liner_fracture
          - implant_thr_THR_atypical_constrained_liner_right
          - implant_thr_THR_atypical_left
          - implant_thr_THR_atypical_long_stem
          - implant_thr_THR_atypical_long_stem_left
          - implant_thr_THR_atypical_long_stem_right
          - implant_thr_THR_atypical_right
          - implant_thr_THR_atypical_short_stem
          - implant_thr_THR_atypical_short_stem_left
          - implant_thr_THR_atypical_short_stem_right
          - implant_thr_THR_cemented_cup
          - implant_thr_THR_cemented_cup_left
          - implant_thr_THR_cemented_cup_right
          - implant_thr_THR_cemented_stem
          - implant_thr_THR_cemented_stem_left
          - implant_thr_THR_cemented_stem_right
          - implant_thr_THR_cup_wear
          - implant_thr_THR_cup_wear_clear
          - implant_thr_THR_cup_wear_clear_left
          - implant_thr_THR_cup_wear_clear_right
          - implant_thr_THR_cup_wear_left
          - implant_thr_THR_cup_wear_right
          - implant_thr_THR_cup_wear_rim
          - implant_thr_THR_cup_wear_suspected
          - implant_thr_THR_cup_wear_suspected_left
          - implant_thr_THR_cup_wear_suspected_right
          - implant_thr_THR_dislocation
          - implant_thr_THR_dislocation_anterior
          - implant_thr_THR_dislocation_lateral
          - implant_thr_THR_dislocation_lateral_left
          - implant_thr_THR_dislocation_lateral_right
          - implant_thr_THR_dislocation_left
          - implant_thr_THR_dislocation_posterior
          - implant_thr_THR_dislocation_posterior_left
          - implant_thr_THR_dislocation_posterior_right
          - implant_thr_THR_dislocation_right
          - implant_thr_THR_fracture
          - implant_thr_THR_fracture_A
          - implant_thr_THR_fracture_A_left
          - implant_thr_THR_fracture_A_right
          - implant_thr_THR_fracture_B1
          - implant_thr_THR_fracture_B1_left
          - implant_thr_THR_fracture_B1_right
          - implant_thr_THR_fracture_B2
          - implant_thr_THR_fracture_B2_right
          - implant_thr_THR_fracture_left
          - implant_thr_THR_fracture_right
          - implant_thr_THR_left
          - implant_thr_THR_osteolysis
          - implant_thr_THR_osteolysis_cup
          - implant_thr_THR_osteolysis_cup_AAOS_I
          - implant_thr_THR_osteolysis_cup_AAOS_I_left
          - implant_thr_THR_osteolysis_cup_AAOS_I_minimal
          - implant_thr_THR_osteolysis_cup_AAOS_I_minimal_left
          - implant_thr_THR_osteolysis_cup_AAOS_I_minimal_right
          - implant_thr_THR_osteolysis_cup_AAOS_I_right
          - implant_thr_THR_osteolysis_cup_AAOS_I_subtotal
          - implant_thr_THR_osteolysis_cup_AAOS_I_subtotal_left
          - implant_thr_THR_osteolysis_cup_AAOS_I_subtotal_right
          - implant_thr_THR_osteolysis_cup_AAOS_I_top-bottom
          - implant_thr_THR_osteolysis_cup_AAOS_I_top-bottom_left
          - implant_thr_THR_osteolysis_cup_AAOS_I_top-bottom_right
          - implant_thr_THR_osteolysis_cup_AAOS_I_total
          - implant_thr_THR_osteolysis_cup_AAOS_I_total_left
          - implant_thr_THR_osteolysis_cup_AAOS_I_total_right
          - implant_thr_THR_osteolysis_cup_AAOS_II
          - implant_thr_THR_osteolysis_cup_AAOS_II_left
          - implant_thr_THR_osteolysis_cup_AAOS_II_right
          - implant_thr_THR_osteolysis_cup_AAOS_III
          - implant_thr_THR_osteolysis_cup_AAOS_III_left
          - implant_thr_THR_osteolysis_cup_AAOS_III_right
          - implant_thr_THR_osteolysis_cup_AAOS_IV
          - implant_thr_THR_osteolysis_cup_AAOS_IV_left
          - implant_thr_THR_osteolysis_cup_AAOS_IV_right
          - implant_thr_THR_osteolysis_cup_left
          - implant_thr_THR_osteolysis_cup_loose
          - implant_thr_THR_osteolysis_cup_loose_left
          - implant_thr_THR_osteolysis_cup_loose_right
          - implant_thr_THR_osteolysis_cup_right
          - implant_thr_THR_osteolysis_cup_rotated
          - implant_thr_THR_osteolysis_cup_rotated_left
          - implant_thr_THR_osteolysis_cup_rotated_right
          - implant_thr_THR_osteolysis_left
          - implant_thr_THR_osteolysis_right
          - implant_thr_THR_osteolysis_stem
          - implant_thr_THR_osteolysis_stem_I
          - implant_thr_THR_osteolysis_stem_I_left
          - implant_thr_THR_osteolysis_stem_I_right
          - implant_thr_THR_osteolysis_stem_II
          - implant_thr_THR_osteolysis_stem_II_both_sides
          - implant_thr_THR_osteolysis_stem_II_both_sides_left
          - implant_thr_THR_osteolysis_stem_II_both_sides_right
          - implant_thr_THR_osteolysis_stem_II_extensive
          - implant_thr_THR_osteolysis_stem_II_extensive_left
          - implant_thr_THR_osteolysis_stem_II_extensive_right
          - implant_thr_THR_osteolysis_stem_II_left
          - implant_thr_THR_osteolysis_stem_II_minimal
          - implant_thr_THR_osteolysis_stem_II_minimal_left
          - implant_thr_THR_osteolysis_stem_II_minimal_right
          - implant_thr_THR_osteolysis_stem_II_one_side
          - implant_thr_THR_osteolysis_stem_II_one_side_left
          - implant_thr_THR_osteolysis_stem_II_one_side_right
          - implant_thr_THR_osteolysis_stem_II_right
          - implant_thr_THR_osteolysis_stem_II_total
          - implant_thr_THR_osteolysis_stem_II_total_left
          - implant_thr_THR_osteolysis_stem_II_total_right
          - implant_thr_THR_osteolysis_stem_III
          - implant_thr_THR_osteolysis_stem_III_left
          - implant_thr_THR_osteolysis_stem_III_right
          - implant_thr_THR_osteolysis_stem_left
          - implant_thr_THR_osteolysis_stem_right
          - implant_thr_THR_right
          - implant_thr_THR_subsidance
          - implant_thr_THR_subsidance_clear
          - implant_thr_THR_subsidance_clear_left
          - implant_thr_THR_subsidance_clear_right
          - implant_thr_THR_subsidance_left
          - implant_thr_THR_subsidance_right
          - implant_thr_THR_subsidance_suspected
          - implant_thr_THR_subsidance_suspected_left
          - implant_thr_THR_subsidance_suspected_right
          - implant_thr_THR_uncemented_cup
          - implant_thr_THR_uncemented_cup_left
          - implant_thr_THR_uncemented_cup_right
          - implant_thr_THR_uncemented_stem
          - implant_thr_THR_uncemented_stem_left
          - implant_thr_THR_uncemented_stem_right
          - implant_TKR
          - implant_Unicompartmental
  #   annotations_path: inner_pseudo_train_2023-12-22.csv
  #   num_jitters: 1
  #   spatial_transform: random
  #   modalities: same_as_train_set
  # max_train_set:
  #   annotations_path: inner_train_max_2023-12-22.csv
  #   num_jitters: 1
  #   spatial_transform: random
  #   modalities: same_as_train_set
  val_set:
    annotations_path: inner_validation_2023-12-22.csv
    num_jitters: 1
    spatial_transform: fix
    modalities: same_as_train_set
  test_set:
    annotations_path: inner_test_2023-12-22.csv
    num_jitters: 1
    spatial_transform: fix
    modalities: same_as_train_set
