---
img_root: xray_root
signal_to_noise_ratio: 0.8
multi_view_per_sample: true
to_each_view_its_own_label: false
experiments:
  train_set:
    annotations_path: inner_train_2023-12-22.csv
    num_jitters: 1
    spatial_transform: random
    shared_modalities:
      - ID
      - text
      - image
      - Exam_View
      - Side
    modalities:
      BP_hand:
        modality: output
        type: Multi_Bipolar
        to_each_view_its_own_label: false
        columns:
          - alt_ao_any_base
          - alt_ao_any_dig_base
          - alt_ao_any_dig_close_to_PIP
          - alt_ao_any_dig_distal
          - alt_ao_any_dig_intermediate
          - alt_ao_any_dig_proximal
          - alt_ao_any_dig_proximal_base_extra_articular
          - alt_ao_any_dig_shaft
          - alt_ao_any_dig_shaft_neck/shaft
          - alt_ao_any_head/tuft
          - alt_ao_any_intra-articular
          - alt_ao_any_oblique
          - alt_ao_any_shaft/waist
          - alt_ao_any_spiral
          - alt_ao_any_transverse
          - alt_ao_metacarpal_base
          - alt_ao_metacarpal_comminuted
          - alt_ao_metacarpal_intra-articular
          - alt_ao_metacarpal_neck
          - alt_ao_metacarpal_oblique
          - alt_ao_metacarpal_shaft
          - alt_ao_metacarpal_simple
          - alt_ao_metacarpal_spiral
          - alt_ao_metacarpal_transverse
          - alt_ao_phalanges_base
          - alt_ao_phalanges_intra-articular
          - alt_ao_phalanges_oblique
          - alt_ao_phalanges_shaft
          - alt_ao_phalanges_transverse
          - alt_ao_phalanges_tuft
          - alt_oa_any
          - alt_oa_any_dig_DIP
          - alt_oa_any_dig_DIP_I_or_II
          - alt_oa_any_dig_DIP_III_or_IV
          - alt_oa_any_dig_I
          - alt_oa_any_dig_I_or_II
          - alt_oa_any_dig_II
          - alt_oa_any_dig_III
          - alt_oa_any_dig_III_or_IV
          - alt_oa_any_dig_IP_I_or_II
          - alt_oa_any_dig_IP_III_or_IV
          - alt_oa_any_dig_IV
          - alt_oa_any_dig_MCP
          - alt_oa_any_dig_MCP_I_or_II
          - alt_oa_any_dig_MCP_III_or_IV
          - alt_oa_any_dig_PIP
          - alt_oa_any_dig_PIP_I_or_II
          - alt_oa_any_dig_PIP_III_or_IV
          - alt_oa_any_III_or_IV
          - alt_oa_CMC-I_I_or_II
          - alt_oa_CMC-I_III_or_IV
          - alt_oa_grade_I
          - alt_oa_grade_II
          - alt_oa_grade_III
          - alt_oa_grade_IV
          - alt_oa_STT_I_or_II
          - alt_oa_STT_III_or_IV
          - ao_dig_1_distal
          - ao_dig_1_distal_base
          - ao_dig_1_distal_base_intra-articular
          - ao_dig_1_distal_shaft
          - ao_dig_1_distal_tuft
          - ao_dig_1_proximal
          - ao_dig_1_proximal_base
          - ao_dig_1_proximal_base_intra-articular
          - ao_dig_1_proximal_base_intra-articular_lateral
          - ao_dig_2_distal
          - ao_dig_2_distal_tuft
          - ao_dig_2_intermediate
          - ao_dig_2_intermediate_base
          - ao_dig_2_intermediate_base_partial_articular
          - ao_dig_2_intermediate_base_partial_articular_volar
          - ao_dig_2_proximal
          - ao_dig_2_proximal_base
          - ao_dig_3_distal
          - ao_dig_3_distal_base
          - ao_dig_3_distal_tuft
          - ao_dig_3_distal_tuft_without_laceration
          - ao_dig_3_intermediate
          - ao_dig_3_intermediate_base
          - ao_dig_3_intermediate_base_partial_articular
          - ao_dig_3_intermediate_base_partial_articular_volar
          - ao_dig_3_proximal
          - ao_dig_3_proximal_base
          - ao_dig_3_proximal_base_intra-articular
          - ao_dig_4_distal
          - ao_dig_4_distal_base
          - ao_dig_4_distal_base_intra-articular
          - ao_dig_4_distal_base_intra-articular_dorsal
          - ao_dig_4_distal_tuft
          - ao_dig_4_distal_tuft_without_laceration
          - ao_dig_4_intermediate
          - ao_dig_4_intermediate_base
          - ao_dig_4_intermediate_base_partial_articular
          - ao_dig_4_intermediate_base_partial_articular_volar
          - ao_dig_4_intermediate_shaft
          - ao_dig_4_proximal
          - ao_dig_4_proximal_base
          - ao_dig_4_proximal_base_extra-articular
          - ao_dig_4_proximal_base_intra-articular
          - ao_dig_4_proximal_neck/shaft
          - ao_dig_4_proximal_neck/shaft_short_oblique
          - ao_dig_5_distal
          - ao_dig_5_distal_base
          - ao_dig_5_distal_base_intra-articular
          - ao_dig_5_distal_base_intra-articular_dorsal
          - ao_dig_5_intermediate
          - ao_dig_5_intermediate_base
          - ao_dig_5_intermediate_base_partial_articular
          - ao_dig_5_intermediate_base_partial_articular_volar
          - ao_dig_5_proximal
          - ao_dig_5_proximal_base
          - ao_dig_5_proximal_base_extra-articular
          - ao_dig_5_proximal_base_intra-articular
          - ao_dig_5_proximal_base_intra-articular_lateral
          - ao_dig_5_proximal_neck/shaft
          - ao_dig_5_proximal_neck/shaft_long_oblique
          - ao_dig_5_proximal_neck/shaft_short_oblique
          - ao_mc_1
          - ao_mc_1_base
          - ao_mc_1_base_simple
          - ao_mc_1_base_simple_Bennett_fracture
          - ao_mc_2
          - ao_mc_2_base
          - ao_mc_2_base_simple
          - ao_mc_2_neck
          - ao_mc_2_neck_simple
          - ao_mc_2_shaft
          - ao_mc_2_shaft_simple
          - ao_mc_3
          - ao_mc_3_base
          - ao_mc_3_base_simple
          - ao_mc_3_neck
          - ao_mc_3_neck_simple
          - ao_mc_3_shaft
          - ao_mc_3_shaft_simple
          - ao_mc_3_shaft_simple_oblique
          - ao_mc_3_shaft_simple_sprial
          - ao_mc_4
          - ao_mc_4_base
          - ao_mc_4_base_simple
          - ao_mc_4_neck
          - ao_mc_4_neck_simple
          - ao_mc_4_shaft
          - ao_mc_4_shaft_simple
          - ao_mc_4_shaft_simple_oblique
          - ao_mc_4_shaft_simple_sprial
          - ao_mc_4_shaft_simple_transverse
          - ao_mc_5
          - ao_mc_5_base
          - ao_mc_5_base_comminuted
          - ao_mc_5_base_comminuted_intra-articular_fracture
          - ao_mc_5_base_simple
          - ao_mc_5_base_simple_reverse_Bennet
          - ao_mc_5_head
          - ao_mc_5_head_simple
          - ao_mc_5_neck
          - ao_mc_5_neck_comminuted
          - ao_mc_5_neck_simple
          - ao_mc_5_shaft
          - ao_mc_5_shaft_comminuted
          - ao_mc_5_shaft_simple
          - ao_mc_5_shaft_simple_oblique
          - ao_mc_5_shaft_simple_sprial
          - ao_mc_5_shaft_simple_transverse
          - ao_proximal_Hamatum
          - ao_proximal_Scaphoid
          - ao_proximal_Scaphoid_displaced
          - ao_proximal_Scaphoid_distal
          - ao_proximal_Scaphoid_proximal
          - ao_proximal_Scaphoid_waist
          - ao_proximal_Triquetrum
          - arthritis_Arthritis
          - arthritis_CMC-I
          - arthritis_CMC-I_I
          - arthritis_CMC-I_II
          - arthritis_CMC-I_III
          - arthritis_CMC-I_IV
          - arthritis_dig_1
          - arthritis_dig_1_IP
          - arthritis_dig_1_IP_I
          - arthritis_dig_1_IP_II
          - arthritis_dig_1_IP_III
          - arthritis_dig_1_IP_IV
          - arthritis_dig_1_MCP
          - arthritis_dig_1_MCP_I
          - arthritis_dig_1_MCP_II
          - arthritis_dig_1_MCP_III
          - arthritis_dig_1_MCP_IV
          - arthritis_dig_2
          - arthritis_dig_2_DIP
          - arthritis_dig_2_DIP_I
          - arthritis_dig_2_DIP_II
          - arthritis_dig_2_DIP_III
          - arthritis_dig_2_DIP_IV
          - arthritis_dig_2_MCP
          - arthritis_dig_2_MCP_I
          - arthritis_dig_2_MCP_II
          - arthritis_dig_2_MCP_III
          - arthritis_dig_2_MCP_IV
          - arthritis_dig_2_PIP
          - arthritis_dig_2_PIP_I
          - arthritis_dig_2_PIP_II
          - arthritis_dig_2_PIP_III
          - arthritis_dig_2_PIP_IV
          - arthritis_dig_3
          - arthritis_dig_3_DIP
          - arthritis_dig_3_DIP_I
          - arthritis_dig_3_DIP_II
          - arthritis_dig_3_DIP_III
          - arthritis_dig_3_DIP_IV
          - arthritis_dig_3_MCP
          - arthritis_dig_3_MCP_I
          - arthritis_dig_3_MCP_II
          - arthritis_dig_3_MCP_III
          - arthritis_dig_3_MCP_IV
          - arthritis_dig_3_PIP
          - arthritis_dig_3_PIP_I
          - arthritis_dig_3_PIP_II
          - arthritis_dig_3_PIP_III
          - arthritis_dig_3_PIP_IV
          - arthritis_dig_4
          - arthritis_dig_4_DIP
          - arthritis_dig_4_DIP_I
          - arthritis_dig_4_DIP_II
          - arthritis_dig_4_DIP_III
          - arthritis_dig_4_DIP_IV
          - arthritis_dig_4_MCP
          - arthritis_dig_4_MCP_I
          - arthritis_dig_4_MCP_II
          - arthritis_dig_4_MCP_IV
          - arthritis_dig_4_PIP
          - arthritis_dig_4_PIP_I
          - arthritis_dig_4_PIP_II
          - arthritis_dig_4_PIP_III
          - arthritis_dig_4_PIP_IV
          - arthritis_dig_5
          - arthritis_dig_5_DIP
          - arthritis_dig_5_DIP_I
          - arthritis_dig_5_DIP_II
          - arthritis_dig_5_DIP_III
          - arthritis_dig_5_DIP_IV
          - arthritis_dig_5_MCP
          - arthritis_dig_5_MCP_I
          - arthritis_dig_5_MCP_II
          - arthritis_dig_5_MCP_III
          - arthritis_dig_5_MCP_IV
          - arthritis_dig_5_PIP
          - arthritis_dig_5_PIP_I
          - arthritis_dig_5_PIP_II
          - arthritis_dig_5_PIP_III
          - arthritis_dig_5_PIP_IV
          - arthritis_DRU
          - arthritis_DRU_I
          - arthritis_DRU_II
          - arthritis_DRU_III
          - arthritis_Radiocarpal
          - arthritis_Radiocarpal_I
          - arthritis_Radiocarpal_II
          - arthritis_Radiocarpal_III
          - arthritis_STT
          - arthritis_STT_I
          - arthritis_STT_II
          - arthritis_STT_III
          - arthritis_STT_IV
          - Fracture
          - general_Arthritis
          - general_Carpus
          - general_Cast
          - general_Cast_minimal
          - general_Cast_plaster
          - general_Dislocation
          - general_Dislocation_Fracture
          - general_Dislocation_PIP
          - general_Dislocation_SL
          - general_Implant
          - general_Metacarpal
          - general_Old
          - general_Old_1-2_weeks
          - general_Old_healed
          - general_Old_pseudo
          - general_Osteopenia
          - general_Phalanx
          - general_Phalanx_1
          - general_Phalanx_2
          - general_Phalanx_3
          - general_Phalanx_4
          - general_Phalanx_5
          - general_Physes
          - general_Radius
          - general_Ulna
          - implant_K-wires
          - implant_Plate
          - implant_Screws
  # pseudo_train_set:
  #   annotations_path: inner_pseudo_train_2023-12-22.csv
  #   num_jitters: 1
  #   spatial_transform: random
  #   modalities: same_as_train_set
  # max_train_set:
  #   annotations_path: inner_train_max_2023-12-22.csv
  #   num_jitters: 1
  #   spatial_transform: random
  #   modalities: same_as_train_set
  val_set:
    annotations_path: inner_validation_2023-12-22.csv
    num_jitters: 1
    spatial_transform: fix
    modalities: same_as_train_set
  test_set:
    annotations_path: inner_test_2023-12-22.csv
    num_jitters: 1
    spatial_transform: fix
    modalities: same_as_train_set
