---
img_root: xray_root
signal_to_noise_ratio: 0.8
multi_view_per_sample: true
to_each_view_its_own_label: false
experiments:
  train_set:
    annotations_path: inner_train_2023-12-22.csv
    num_jitters: 1
    spatial_transform: random
    shared_modalities:
      - ID
      - text
      - image
      - Exam_View
    modalities:
      BP_hip:
        modality: output
        type: Multi_Bipolar
        to_each_view_its_own_label: false
        columns:
          - alt_ao_hip_A12_or_B3_any
          - alt_ao_hip_A12_or_B3_left
          - alt_ao_hip_A12_or_B3_right
          - alt_ao_hip_A22_A23_or_A33_any
          - alt_ao_hip_A22_A23_or_A33_left
          - alt_ao_hip_A22_A23_or_A33_right
          - alt_ao_hip_B_dislocated_any
          - alt_ao_hip_B_dislocated_left
          - alt_ao_hip_B_dislocated_right
          - alt_osteoarthritis_0_to_1_any
          - alt_osteoarthritis_0_to_1_left
          - alt_osteoarthritis_0_to_1_right
          - alt_osteoarthritis_0_to_2_any
          - alt_osteoarthritis_0_to_2_left
          - alt_osteoarthritis_0_to_2_right
          - alt_osteoarthritis_1_to_2_any
          - alt_osteoarthritis_1_to_2_left
          - alt_osteoarthritis_1_to_2_right
          - alt_osteoarthritis_1_to_3_any
          - alt_osteoarthritis_1_to_3_left
          - alt_osteoarthritis_1_to_3_right
          - alt_osteoarthritis_2_to_3_any
          - alt_osteoarthritis_2_to_3_left
          - alt_osteoarthritis_2_to_3_right
          - alt_osteoarthritis_3_to_4_any
          - alt_osteoarthritis_3_to_4_left
          - alt_osteoarthritis_3_to_4_right
          - alt_osteoarthritis_highest_0
          - alt_osteoarthritis_highest_1
          - alt_osteoarthritis_highest_2
          - alt_osteoarthritis_highest_3
          - alt_osteoarthritis_highest_4
          - ao_acetabulum_A_any
          - ao_acetabulum_any
          - ao_acetabulum_B_any
          - ao_acetabulum_B_left
          - ao_acetabulum_B_right
          - ao_acetabulum_B1_any
          - ao_acetabulum_B1_left
          - ao_acetabulum_B1_right
          - ao_acetabulum_B12_any
          - ao_acetabulum_B12_left
          - ao_acetabulum_B12_right
          - ao_acetabulum_B2_any
          - ao_acetabulum_B2_left
          - ao_acetabulum_B22_any
          - ao_acetabulum_B22_left
          - ao_acetabulum_left
          - ao_acetabulum_right
          - ao_femur_A_any
          - ao_femur_A_left
          - ao_femur_A_right
          - ao_femur_A1_any
          - ao_femur_any
          - ao_femur_B_any
          - ao_femur_B2_any
          - ao_femur_left
          - ao_femur_proximal_any
          - ao_femur_proximal_left
          - ao_femur_proximal_right
          - ao_femur_right
          - ao_hip_A_any
          - ao_hip_A_left
          - ao_hip_A_right
          - ao_hip_A1_any
          - ao_hip_A1_left
          - ao_hip_A1_right
          - ao_hip_A11_any
          - ao_hip_A11_left
          - ao_hip_A11_right
          - ao_hip_A12_any
          - ao_hip_A12_dislocated_any
          - ao_hip_A12_dislocated_left
          - ao_hip_A12_dislocated_right
          - ao_hip_A12_left
          - ao_hip_A12_right
          - ao_hip_A12_trochanter_major_any
          - ao_hip_A12_trochanter_major_left
          - ao_hip_A12_trochanter_major_right
          - ao_hip_A13_any
          - ao_hip_A13_dislocated_any
          - ao_hip_A13_dislocated_left
          - ao_hip_A13_dislocated_right
          - ao_hip_A13_left
          - ao_hip_A13_right
          - ao_hip_A13_trochanter_major_any
          - ao_hip_A13_trochanter_major_left
          - ao_hip_A13_trochanter_major_right
          - ao_hip_A2_any
          - ao_hip_A2_left
          - ao_hip_A2_right
          - ao_hip_A22_any
          - ao_hip_A22_dislocated_any
          - ao_hip_A22_dislocated_left
          - ao_hip_A22_dislocated_right
          - ao_hip_A22_left
          - ao_hip_A22_long_minor_any
          - ao_hip_A22_long_minor_left
          - ao_hip_A22_long_minor_right
          - ao_hip_A22_right
          - ao_hip_A23_any
          - ao_hip_A23_left
          - ao_hip_A23_right
          - ao_hip_A3_any
          - ao_hip_A3_left
          - ao_hip_A3_right
          - ao_hip_A31_any
          - ao_hip_A31_left
          - ao_hip_A31_right
          - ao_hip_A32_any
          - ao_hip_A32_left
          - ao_hip_A32_right
          - ao_hip_A33_any
          - ao_hip_A33_diaphysis_any
          - ao_hip_A33_diaphysis_left
          - ao_hip_A33_diaphysis_right
          - ao_hip_A33_left
          - ao_hip_A33_right
          - ao_hip_A33_trochanter_major_any
          - ao_hip_A33_trochanter_major_left
          - ao_hip_A33_trochanter_major_right
          - ao_hip_any
          - ao_hip_B_any
          - ao_hip_B_left
          - ao_hip_B_right
          - ao_hip_B1_any
          - ao_hip_B1_left
          - ao_hip_B1_right
          - ao_hip_B11_any
          - ao_hip_B11_left
          - ao_hip_B11_right
          - ao_hip_B12_any
          - ao_hip_B12_left
          - ao_hip_B12_right
          - ao_hip_B13_any
          - ao_hip_B13_left
          - ao_hip_B13_right
          - ao_hip_B2_any
          - ao_hip_B2_left
          - ao_hip_B2_right
          - ao_hip_B21_any
          - ao_hip_B21_dislocated_any
          - ao_hip_B21_dislocated_left
          - ao_hip_B21_dislocated_right
          - ao_hip_B21_left
          - ao_hip_B21_right
          - ao_hip_B22_any
          - ao_hip_B22_dislocated_any
          - ao_hip_B22_dislocated_left
          - ao_hip_B22_dislocated_right
          - ao_hip_B22_left
          - ao_hip_B22_right
          - ao_hip_B23_any
          - ao_hip_B23_dislocated_any
          - ao_hip_B23_dislocated_left
          - ao_hip_B23_dislocated_right
          - ao_hip_B23_left
          - ao_hip_B23_right
          - ao_hip_B3_any
          - ao_hip_B3_left
          - ao_hip_B3_right
          - ao_hip_left
          - ao_hip_right
          - ao_pelvic_A
          - ao_pelvic_A2
          - ao_pelvic_A22
          - ao_pelvic_any
          - ao_pelvic_left
          - ao_pelvic_right
          - Fracture
          - general_Acetabulum
          - general_AVN
          - general_AVN_any
          - general_AVN_left
          - general_AVN_right
          - general_DHS
          - general_DHS_any
          - general_DHS_left
          - general_DHS_right
          - general_Dislocation
          - general_Dislocation_any
          - general_Dislocation_left
          - general_Dislocation_right
          - general_Femur_diaphysis
          - general_Hemi
          - general_Hemi_any
          - general_Hemi_left
          - general_Hemi_right
          - general_Hip
          - general_IM-nail
          - general_IM-nail_any
          - general_IM-nail_left
          - general_IM-nail_right
          - general_Implant
          - general_Implant_failure
          - general_Old_fracture
          - general_Old_fracture_any
          - general_Old_fracture_left
          - general_Old_fracture_right
          - general_Osteolysis
          - general_Osteolysis_any
          - general_Osteolysis_left
          - general_Osteolysis_right
          - general_Pathological_fracture
          - general_Pathological_fracture_any
          - general_Pelvic_ring
          - general_Peri-implant_fracture
          - general_Peri-implant_fracture_any
          - general_Peri-implant_fracture_right
          - general_Screws
          - general_Screws_any
          - general_Screws_left
          - general_Screws_right
          - general_THR
          - general_THR_any
          - general_THR_left
          - general_THR_right
          - general_Tumor
          - general_Tumor_malignant
          - osteoarthritis_0_any
          - osteoarthritis_0_left
          - osteoarthritis_0_right
          - osteoarthritis_1_any
          - osteoarthritis_1_left
          - osteoarthritis_1_right
          - osteoarthritis_2_any
          - osteoarthritis_2_left
          - osteoarthritis_2_right
          - osteoarthritis_3_any
          - osteoarthritis_3_left
          - osteoarthritis_3_right
          - osteoarthritis_4_any
          - osteoarthritis_4_left
          - osteoarthritis_4_right
          - osteoarthritis_any
          - osteoarthritis_left
          - osteoarthritis_right
  # pseudo_train_set:
  #   annotations_path: inner_pseudo_train_2023-12-22.csv
  #   num_jitters: 1
  #   spatial_transform: random
  #   modalities: same_as_train_set
  # max_train_set:
  #   annotations_path: inner_train_max_2023-12-22.csv
  #   num_jitters: 1
  #   spatial_transform: random
  #   modalities: same_as_train_set
  val_set:
    annotations_path: inner_validation_2023-12-22.csv
    num_jitters: 1
    spatial_transform: fix
    modalities: same_as_train_set
  test_set:
    annotations_path: inner_test_2023-12-22.csv
    num_jitters: 1
    spatial_transform: fix
    modalities: same_as_train_set
