---
img_root: xray_root
signal_to_noise_ratio: 0.8
multi_view_per_sample: true
to_each_view_its_own_label: false
experiments:
  train_set:
    annotations_path: inner_train_2023-12-22.csv
    num_jitters: 1
    spatial_transform: random
    shared_modalities:
      - ID
      - text
      - image
      - Exam_View
      - Side
      - Body_Part
    modalities:
      BP_hot:
        modality: output
        type: Multi_Bipolar
        to_each_view_its_own_label: false
        columns:
          - alt_frx_detail_displace_bad
          - alt_frx_detail_displace_ok
          - alt_frx_detail_oblique_spiral
          - alt_frx_detail_transverse_or_wedge
          - Fracture
          - frx_detail_Angulation
          - frx_detail_Callus
          - frx_detail_Cast
          - frx_detail_Cast_minimal
          - frx_detail_Cast_plaster
          - frx_detail_Cast_synthetic
          - frx_detail_Comminute
          - frx_detail_Dislocation
          - frx_detail_Displaced
          - frx_detail_Extra-articular
          - frx_detail_Failure
          - frx_detail_Failure_major
          - frx_detail_Failure_minor
          - frx_detail_Fixed
          - frx_detail_Fracture
          - frx_detail_Fragment
          - frx_detail_Implant
          - frx_detail_Intra-articular
          - frx_detail_Multiple
          - frx_detail_Oblique
          - frx_detail_Previous
          - frx_detail_Previous_1-3w
          - frx_detail_Previous_3_w+
          - frx_detail_Previous_healed
          - frx_detail_Pseudo
          - frx_detail_Slightly_displaced
          - frx_detail_Spiral
          - frx_detail_Transverse
          - frx_detail_Undisplaced
          - frx_detail_Wedge
          - implant_Anchor
          - implant_Arthroplasty
          - implant_Cerclage
          - implant_Collapse
          - implant_Cut-out
          - implant_DHS
          - implant_Fixation_failure
          - implant_Hardware_fracture
          - implant_Hardware_migration
          - implant_Hemi
          - implant_IM-nail
          - implant_IM-nail_femur
          - implant_IM-nail_tibia
          - implant_Implant_failure
          - implant_Insignificant
          - implant_K-wires
          - implant_Nail
          - implant_Osteolysis
          - implant_Peri-implant_fracture
          - implant_Plate
          - implant_Screws
          - implant_Staple
          - implant_THR
          - implant_TKR
          - implant_Unicompartmental
          - implant_X-fix
  # pseudo_train_set:
  #   annotations_path: inner_pseudo_train_2023-12-22.csv
  #   num_jitters: 1
  #   spatial_transform: random
  #   modalities: same_as_train_set
  # max_train_set:
  #   annotations_path: inner_train_max_2023-12-22.csv
  #   num_jitters: 1
  #   spatial_transform: random
  #   modalities: same_as_train_set
  val_set:
    annotations_path: inner_validation_2023-12-22.csv
    num_jitters: 1
    spatial_transform: fix
    modalities: same_as_train_set
